# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoRegistrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.CharField(max_length=140)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
